name: CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test-and-build:
    runs-on: ubuntu-latest

    services:
      mongodb:
        image: mongo:4.4
        ports:
          - 27017:27017

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Install dependencies
        run: |
          cd services/auth-service
          npm ci

      - name: Run tests
        run: |
          cd services/auth-service
          npm test
        env:
          MONGODB_URI: mongodb://localhost:27017/auth-service-test
          JWT_SECRET: test-secret

      - name: Build Docker images
        run: |
          cd services/auth-service
          docker build -t auth-service:${{ github.sha }} .

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Push Docker images
        run: |
          cd services/auth-service
          docker tag auth-service:${{ github.sha }} ${{ secrets.DOCKER_HUB_USERNAME }}/auth-service:${{ github.sha }}
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/auth-service:${{ github.sha }}
